### ISSUE TITLE
Albums / playlist in LMS favorites are shown as spotify URL

### ISSUE THREAD

**Issue by Mrpink200** [michaelherger/spotty#28]
Hi Michael.

I guess i found a bug 
I was playing with your great LMS plugin and had the idea to add some playlists / and or / albums to LMS favorites (as it is allowed).
I found that the result was that the track information were shown as urls and not the track names.
Are you aware of this ?

here 2 examples : one with a playlist , one with an album
i use the skin material on iphone, but it iw the same with standard LMS skin on desktop
![Image](https://user-images.githubusercontent.com/7417251/111474825-bdf20e00-872c-11eb-8082-8c7433b27be4.png)
![Image-1](https://user-images.githubusercontent.com/7417251/111474842-c3e7ef00-872c-11eb-9b96-e3e317a95fd9.png)
![Image-2](https://user-images.githubusercontent.com/7417251/111474854-c6e2df80-872c-11eb-8909-896e4222808e.png)

**Comment by michaelherger** [comment]
Did you test adding the favourites with all those UIs? I believe it's the responsibility of whoever is asking LMS to mark a track as a favourite to add the name to it.

**Comment by Mrpink200** [comment]
I ve just click add to favorites :
![image](https://user-images.githubusercontent.com/7417251/111476069-107ffa00-872e-11eb-82bd-0e981247b64b.png)

**Comment by Mrpink200** [comment]
What is stange is that the album artist or playlist are shown ok but not the tracks

**Comment by michaelherger** [comment]
Can you try saving a favourite using the default web UI? Or anything other than the Material skin?

**Comment by Mrpink200** [comment]
Sure :

![image](https://user-images.githubusercontent.com/7417251/111478658-90a75f00-8730-11eb-9b4a-fd5246d5636a.jpeg)
![image](https://user-images.githubusercontent.com/7417251/111478687-98670380-8730-11eb-9f0a-cf9cb41bd806.jpeg)

Why closing the topic ?

**Comment by michaelherger** [comment]
I'm sorry, accidentally hit the "close with comment" button, rather than just "comment".

Ok, I'll have to look into this. I'm pretty sure this used to work before. What I'm a bit confused about is that this issues' title says "Albums in LMS favourites are shown as Spotify URL", but all screenshots actually show tracks?

**Comment by Mrpink200** [comment]
sorry, about the confusion, fonna ypdate the title : )

**Comment by Mrpink200** [comment]
hello @michaelherger . any news in your investigations ? :)

**Comment by michaelherger** [comment]
I'm sorry, this is not a priority. As with LMS8 you can import your Spotify favourites, using the favorites in LMS is a bit of an odd use case.

But I can confirm that if I favourite a Spotify album, and I then drill down in to this album (and I guess playlists would behave the same), I only see the URIs instead of track titles etc.
