### ISSUE TITLE
Spotty helper fails to load

### ISSUE THREAD

**Issue by amaskell999** [michaelherger/spotty#29]
I'm running LMS v8.2.0 on a Windows 10 server. Spotty always used to work fine but earlier this year it stopped working. I now get this warning coming up on the settings page:

There has been a problem running the Spotty helper application. Please make sure you have the Microsoft Visual C++ Runtime (64-bit!) installed on your system.

Unfortunately, I'm only running a 32-bit operating system so I can't install the 64-bit libraries. Is there another way around this other than upgrading Windows 10 to 64-bit?

Thanks, Andy.

**Comment by michaelherger** [comment]
You can download the old 32-bit version from https://github.com/michaelherger/Spotty-Plugin/blob/e2a9c2c33e68368a78abae8dceb4c40918dbd238/Bin/MSWin32-x86-multi-thread/spotty.exe?raw=true. Then store it in a place in your search path (see Settings/Information), but _outside_ the LMS managed folders. That should make the plugin pick it up instead of the 64-bit version. But you'd obviously loose new improvements/features.

Unfortunately rust doesn't allow me to compile 32-bit on 64-bit systems any more.
